"""initial

Revision ID: 7aa7de03a00a
Revises: 
Create Date: 2026-07-20 14:32:18.565604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7aa7de03a00a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('screen_width', sa.Integer(), nullable=False),
    sa.Column('screen_height', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('bot_detection', sa.Boolean(), nullable=False),
    sa.Column('authenticate_user_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_access_fingerprint'), 'analytics_access', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_analytics_access_session_id'), 'analytics_access', ['session_id'], unique=False)
    op.create_table('invests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('proposal', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invests_email'), 'invests', ['email'], unique=True)
    op.create_table('monitoring_target',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('incident',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monitoring_target_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='incidentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_target_id'], ['monitoring_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('CAPTURED', 'PROCESSING', 'VALIDATED', 'FAILED', name='evidencestatus'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_hash'), 'evidence', ['hash'], unique=False)
    op.create_index(op.f('ix_evidence_incident_id'), 'evidence', ['incident_id'], unique=False)
    op.create_index(op.f('ix_evidence_status'), 'evidence', ['status'], unique=False)
    op.create_table('evidence_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('html_path', sa.String(length=500), nullable=False),
    sa.Column('screenshot_path', sa.String(length=500), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_snapshots_evidence_id'), 'evidence_snapshots', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_snapshots_hash'), 'evidence_snapshots', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_snapshots_hash'), table_name='evidence_snapshots')
    op.drop_index(op.f('ix_evidence_snapshots_evidence_id'), table_name='evidence_snapshots')
    op.drop_table('evidence_snapshots')
    op.drop_index(op.f('ix_evidence_status'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_incident_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_hash'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('incident')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('monitoring_target')
    op.drop_index(op.f('ix_invests_email'), table_name='invests')
    op.drop_table('invests')
    op.drop_index(op.f('ix_analytics_access_session_id'), table_name='analytics_access')
    op.drop_index(op.f('ix_analytics_access_fingerprint'), table_name='analytics_access')
    op.drop_table('analytics_access')
    # ### end Alembic commands ###
