"""add city to analytics_access

Revision ID: 805262a40365
Revises: b95349ec28f3
Create Date: 2026-06-09 23:27:47.063241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '805262a40365'
down_revision: Union[str, Sequence[str], None] = 'b95349ec28f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_access', sa.Column('city', sa.String(length=100), nullable=True))
    op.alter_column('analytics_access', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('analytics_access', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('analytics_access', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_analytics_access_ip_address'), table_name='analytics_access')
    op.drop_index(op.f('ix_analytics_access_sessionId'), table_name='analytics_access')
    op.create_index(op.f('ix_analytics_access_session_id'), 'analytics_access', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_access_session_id'), table_name='analytics_access')
    op.create_index(op.f('ix_analytics_access_sessionId'), 'analytics_access', ['session_id'], unique=False)
    op.create_index(op.f('ix_analytics_access_ip_address'), 'analytics_access', ['ip_address'], unique=False)
    op.alter_column('analytics_access', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('analytics_access', 'user_agent',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('analytics_access', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('analytics_access', 'city')
    # ### end Alembic commands ###
