"""init

Revision ID: 94bc068f61c2
Revises: 
Create Date: 2026-06-24 01:14:29.699503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94bc068f61c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('screen_width', sa.Integer(), nullable=False),
    sa.Column('screen_height', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('bot_detection', sa.Boolean(), nullable=False),
    sa.Column('authenticate_user_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_access_fingerprint'), 'analytics_access', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_analytics_access_session_id'), 'analytics_access', ['session_id'], unique=False)
    op.create_table('digital_evidences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('CAPTURED', 'PROCESSING', 'VALIDATED', 'FAILED', name='evidencestatus'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_evidences_hash'), 'digital_evidences', ['hash'], unique=False)
    op.create_index(op.f('ix_digital_evidences_status'), 'digital_evidences', ['status'], unique=False)
    op.create_table('invests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('proposal', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invests_email'), 'invests', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_invests_email'), table_name='invests')
    op.drop_table('invests')
    op.drop_index(op.f('ix_digital_evidences_status'), table_name='digital_evidences')
    op.drop_index(op.f('ix_digital_evidences_hash'), table_name='digital_evidences')
    op.drop_table('digital_evidences')
    op.drop_index(op.f('ix_analytics_access_session_id'), table_name='analytics_access')
    op.drop_index(op.f('ix_analytics_access_fingerprint'), table_name='analytics_access')
    op.drop_table('analytics_access')
    # ### end Alembic commands ###
