"""create analytics_access table

Revision ID: b95349ec28f3
Revises: 383a9988902a
Create Date: 2026-05-24 15:52:18.743234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b95349ec28f3'
down_revision: Union[str, Sequence[str], None] = '383a9988902a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
