"""create invest table

Revision ID: c69d8667ea24
Revises: 
Create Date: 2026-05-08 02:21:10.440600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c69d8667ea24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('proposal', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invests_email'), 'invests', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invests_email'), table_name='invests')
    op.drop_table('invests')
    # ### end Alembic commands ###
