from src.module.digital_evidence.application.command.evidence_snapshot_create_cmd import EvidenceSnapshotCreateCommand
from src.module.digital_evidence.application.service_use_case.evidence


class EvidenceSnapshotCreateHandler():
